---
- name: Install Docker reqs
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release
    - curl
  
- name: Add to official GPG key 
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
 

- name: Setup the official repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
- name: Install docker
  apt:
    update_cache: yes
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Copy docker files
  ansible.builtin.copy:
    src: /vagrant/docker
    dest: /home/cc

- name: Rename directory
  command: mv /home/cc/docker /home/cc/dockerfiles

- name: Copy consumer.py
  ansible.builtin.copy:
    src: ~/consumer.py
    dest: /home/cc/dockerfiles/consumer.py
...
